#!/usr/bin/env sh

source $HOME/.config/sketchybar/colors.sh

CURRENT_MODE=$(cat ~/.config/skhd/currentMode.txt)

case $CURRENT_MODE in
  "DEFAULT") BACKGROUND_COLOR=$BLUE; FOREGROUND_COLOR=$BACKGROUND; MODE_NAME="Df" ;;
  "STACK") BACKGROUND_COLOR=$RED; FOREGROUND_COLOR=$FOREGROUND; MODE_NAME="St" ;;
  "LAUNCH") BACKGROUND_COLOR=$CYAN; FOREGROUND_COLOR=$BACKGROUND; MODE_NAME="Ln" ;;
  "RESIZE") BACKGROUND_COLOR=$GREEN; FOREGROUND_COLOR=$FOREGROUND; MODE_NAME="Rs" ;;
  "PLACE") BACKGROUND_COLOR=$YELLOW ; FOREGROUND_COLOR=$BACKGROUND; MODE_NAME="Pl" ;;
  "WARP") BACKGROUND_COLOR=$MAGENTA ; FOREGROUND_COLOR=$BACKGROUND; MODE_NAME="Wr" ;;
  "INSERT") BACKGROUND_COLOR=$BLACK ; FOREGROUND_COLOR=$FOREGROUND; MODE_NAME="In" ;;
  "FLOAT") BACKGROUND_COLOR=$FOREGROUND ; FOREGROUND_COLOR=$BACKGROUND; MODE_NAME="Fl" ;;
  "SETTINGS") BACKGROUND_COLOR=$CYAN ; FOREGROUND_COLOR=$BLACK; MODE_NAME="Se" ;;
esac

sketchybar --set $NAME label="$CURRENT_MODE" \
                        label.color=$FOREGROUND_COLOR \
                        background.color=$BACKGROUND_COLOR
